local kit = require("lua.productshotai_site_kit")
assert(kit.BASE == "https://productshotai.app")
assert(kit.BRAND == "ProductShot AI")
assert(kit.home_url() == "https://productshotai.app/")
assert(kit.workbench_url() == "https://productshotai.app/#workbench")
assert(kit.pricing_url() == "https://productshotai.app/#pricing")
assert(kit.blog_url() == "https://productshotai.app/blog/")
assert(kit.localized_url("en", "/blog") == "https://productshotai.app/blog/")
assert(kit.localized_url("zh-CN", "blog") == "https://productshotai.app/zh/blog/")
assert(kit.metadata().name == "ProductShot AI")
local ok = pcall(function() kit.localized_url("fr", "/blog") end)
assert(not ok)
print("lua tests passed")
